# This is a basic workflow to help you get started with Actions

name: Deploy Server

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out the repository
      - name: Pull changes
        working-directory: /docker
        run: echo $PWD && git pull
        
      # Deploys the docker containers
      - name: Deploy application
        shell: bash
        env:
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
        working-directory: /docker
        run: docker-compose up -d

